Add back some lighttpd support
make it easier to install the Mic webinterface

diff --git a/debian/readsb.postinst b/debian/readsb.postinst
--- a/debian/readsb.postinst
+++ b/debian/readsb.postinst
@@ -36,6 +36,24 @@ case "$1" in
 	# dialout required for Mode-S Beast and GNS5894 ttyAMA0 access
 	adduser "$RUNAS" dialout
 
+        # set up lighttpd
+        if dpkg --compare-versions "$2" lt "3.1.0"
+        then
+            echo "Enabling lighttpd integration.." >&2
+            lighty-enable-mod readsb || true
+
+            # only enable the statcache config if there is nothing else around that already
+            # configures it, because lighttpd fails if it's configured twice
+            if ! grep -q -E '^\S*server.stat-cache-engine' /etc/lighttpd/conf-enabled/*.conf
+            then
+                echo "Enabling lighttpd integration (stat cache).." >&2
+                lighty-enable-mod readsb-statcache || true
+            fi
+        fi
+
+        echo "Restarting lighttpd.." >&2
+        invoke-rc.d lighttpd force-reload || true
+        invoke-rc.d lighttpd restart || true
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
diff --git a/debian/readsb.postrm b/debian/readsb.postrm
--- a/debian/readsb.postrm
+++ b/debian/readsb.postrm
@@ -28,6 +28,27 @@ case "$1" in
         ;;
 
     remove)
+        changed=false
+        if [ -e /etc/lighttpd/conf-enabled/89-readsb.conf ]
+        then
+            echo "Disabling lighttpd integration.." >&2
+            lighty-disable-mod readsb || true
+            changed=true
+        fi
+
+        if [ -e /etc/lighttpd/conf-enabled/88-readsb-statcache.conf ]
+        then
+            echo "Disabling lighttpd integration (stat cache).." >&2
+            lighty-disable-mod readsb-statcache || true
+            changed=true
+        fi
+
+        if $changed
+        then
+            echo "Restarting lighttpd.." >&2
+            invoke-rc.d lighttpd force-reload || echo "Warning: lighttpd failed to reload configuration." >&2
+            invoke-rc.d lighttpd restart || echo "Warning: lighttpd failed to restart." >&2
+        fi
         ;;
 
     upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
